apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-stack-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: elk-stack-project
  source:
    path: kubernetes/argocd-apps
    repoURL: git@github.com:raphaelmulenda/elk-stack-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true