apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elastic-system
    server: https://kubernetes.default.svc
  project: elk-stack
  source:
    path: kubernetes/apps/eck-operator
    repoURL: git@github.com:raphaelmulenda/elk-stack-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
