apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: elk-stack-project
  source:
    repoURL: git@github.com:raphaelmulenda/elk-stack-apps.git
    targetRevision: HEAD
    path: kubernetes/apps/game-test/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: game-test-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true