argocd-apps:
  projects:
    elk-stack-project:
      namespace: argocd
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      orphanedResources:
        warn: false

  # applications:
  #   elk-stack-app:
  #     namespace: argocd
  #     project: elk-stack-project
  #     source:
  #       repoURL: git@github.com:raphaelmulenda/elk-stack-apps.git
  #       targetRevision: HEAD
  #       path: kubernetes/argoproj/
  #     destination:
  #       server: https://kubernetes.default.svc
  #       namespace: argocd
  #     syncPolicy:
  #       syncOptions:
  #         - CreateNamespace=true
  #       automated:
  #         prune: true
  #         selfHeal: true
